# Generated by Django 3.2.5 on 2021-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=255)),
                ('surface', models.FloatField()),
                ('population', models.IntegerField()),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=2038)),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('preparation_time', models.FloatField()),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=2038)),
            ],
        ),
    ]
