# Generated by Django 3.2.5 on 2021-07-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('europa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='dish_country',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
